name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      KAFKA_SERVICE_URI: ${{ secrets.KAFKA_SERVICE_URI }}
    steps:
      - name: Setting secrets
        env:
          SSL_CA_FILE: ${{ secrets.SSL_CA_FILE }}
          SSL_CERTFILE: ${{ secrets.SSL_CERTFILE }}
          SSL_KEYFILE: ${{ secrets.SSL_KEYFILE }}
        run: |
            'echo "$SSL_CA_FILE" > /tmp/ca.pem'
            'echo "SSL_CERTFILE" > /tmp/service.cert'
            'echo "SSL_KEYFILE" > /tmp/service.key'
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        id: python-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements
          python -m pip install flake8
      - name: Lint with flake8
        id: flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=88 --statistics
      - name: Test with pytest
        env:
          SSL_CA_FILE: /tmp/ca.pem
          SSL_CERTFILE: /tmp/service.cert
          SSL_KEYFILE: /tmp/service.key
        id: tests
        run: |
          python -m pytest